default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: cnd_fin_track_development
test:
  <<: *default
  database: cnd_fin_track_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("POSTGRES_DB", "cnd_fin_track_production") %>
    username: <%= ENV.fetch("POSTGRES_USER", "cnd_fin_track") %>
    password: <%= ENV["POSTGRES_PASSWORD"] %>
    host: <%= ENV.fetch("POSTGRES_HOST", "cnd_fin_track-db") %>
    port: <%= ENV.fetch("POSTGRES_PORT", 5433) %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "cnd_fin_track_production") %>_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "cnd_fin_track_production") %>_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "cnd_fin_track_production") %>_cable
    migrations_paths: db/cable_migrate
  logs:
    <<: *primary_production
    database: <%= ENV.fetch("POSTGRES_DB", "cnd_fin_track_production") %>_logs
    migrations_paths: db/logs_migrate
