# Name of your application. Used to uniquely configure containers.
service: cnd_fin_track

image: ghcr.io/changendevops/cndfintrack

registry:
  server: ghcr.io
  username: <%= ENV["KAMAL_REGISTRY_USERNAME"] %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PORT
    - KAMAL_REGISTRY_PASSWORD
    - MEILI_MASTER_KEY
    - POSTGRES_HOST
    - MEILISEARCH_API_KEY
  clear:
    SOLID_QUEUE_IN_PUMA: true
    PORT: 8080
    BACKEND_PORT: 8080
    HOST: <%= ENV["HOST"] %>
    RAILS_LOG_LEVEL: debug
    RAILS_ENV: production
    MEILISEARCH_HOST: http://cnd_fin_track-meilisearch:7700

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "cnd_fin_track_storage:/rails/storage"
  - "meili_data:/meili_data"

asset_path: /rails/public/assets

# Configure the image builder.
builder:
  arch: amd64

  secrets:
    - KAMAL_REGISTRY_PASSWORD
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - POSTGRES_DB
    - POSTGRES_PORT
    - HOST
    - MEILI_MASTER_KEY
    - POSTGRES_HOST

accessories:
  db:
    image: postgres:18
    host: 158.69.116.112
    port: "5433"
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_USER
      clear:
        PGPORT: 5433
        DB_HOST: <%= ENV.fetch("POSTGRES_HOST", "cnd_fin_track-db") %>
    volumes:
      - prod-cnd_fin_track:/var/lib/postgresql
  meilisearch:
    image: getmeili/meilisearch:v1.52
    roles:
      - web
    port: "7700:7700"
    env:
      clear:
        MEILI_ENV: production
        MEILI_NO_ANALYTICS: "true"
        MEILI_UPGRADE_DB: "true"
      secret:
        - MEILI_MASTER_KEY
    volumes:
      - prod-cnd_fin_track_meilisearch:/meili_data