servers:
  web:
    hosts:
      - 158.69.116.112

boot:
  wait: 60

proxy:
  ssl: true
  host: cndfintrack.c-devops.com
  app_port: 8080

accessories:
  db:
    image: postgres:18
    host: 158.69.116.112
    port: 5433
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        DB_HOST: db-postgres
        POSTGRES_DB: <%= ENV.fetch("POSTGRES_DB", "cnd_fin_track_production") %>
        POSTGRES_USER: <%= ENV.fetch("POSTGRES_USER", "cnd_fin_track") %>
        POSTGRES_PORT: <%= ENV.fetch("POSTGRES_PORT", "5433") %>
    volumes:
      - prod-cnd_fin_track:/var/lib/postgresql

ssh:
  user: fintrack
