servers:
  web:
    hosts:
      - 158.69.116.112

boot:
  wait: 60

proxy:
  ssl: true
  host: cndfintrack.c-devops.com
  app_port: 8080

accessories:
  db:
    image: postgres:18
    host: 158.69.116.112
    port: "5433:5432"
    env:
      secret:
        - POSTGRES_PASSWORD
        - POSTGRES_DB
        - POSTGRES_USER
      clear:
        DB_HOST: <%= ENV.fetch("POSTGRES_HOST", "cnd_fin_track-db") %>
    volumes:
      - prod-cnd_fin_track:/var/lib/postgresql

ssh:
  user: fintrack
